# Site settings
title: club d'informatique
description: since 2019-2022
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. httpgrace a://willianjusten.com.br

# User settings
username: club-infoAbriand

user_description: Club d'informatique a Aristide briand. Ce club a etait cree pour que differents eleves puissent cooperer pour creer un project grace a leur connaissance et travail d'equipe pour qu'il puisse servir au club ou au lycee.
user_title: club d'informatique
email: club.informatiqueabriand@gmail.com
# twitter_username: lorem_ipsum
github_username: club-infoAbriand
instagram_username:  club.info_ab

exclude: ['package.json', 'src' , 'node_modules']
