# Site settings
title: club d'informatique
description: since 2019-2022
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. httpgrace a://command.Z3R0.com.br

# User settings
username: club-infoAbriand

user_description: Club informatique à Aristide Briand. Ce club a été créé afin que différents étudiants puissent coopérer pour créer un projet grâce à leurs connaissances et leur travail d'équipe afin qu'il puisse servir le club ou le lycée.
user_title: club d'informatique
email: club.informatiqueabriand@gmail.com
# twitter_username: command.Z3R0
github_username: club-infoAbriand
instagram_username:  club.info_ab

exclude: ['package.json', 'src' , 'node_modules']
